# Generated by Django 5.2.5 on 2025-08-17 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_ton_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoclaimSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('1w', '1 неделя'), ('1m', '1 месяц'), ('6m', '6 месяцев')], max_length=8)),
                ('active_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
