# Generated by Django 5.2.5 on 2025-08-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ton_address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('ton_address__isnull', False), models.Q(('ton_address', ''), _negated=True)), fields=('ton_address',), name='uniq_nonempty_ton_address'),
        ),
    ]
